// コマンドオプションの定義

module.exports = {
  引数あり: [
    ['-b', '--brackets'],
    ['-g', '--grade'],
    ['-G', '--granularity'],
    ['-s', '--selector'],
    ['-n', '--not-selector'],
    ['-N', '--ng-elements'],
    ['-T', '--title'],
    ['-L', '--headline'],
    //
    ['-r', '--ruby'],
    ['--ruby-comma'],
    ['--ruby-re'],
  ],
  引数なし: [
    ['-d', '--debug'],
    ['-h', '--help'],
    ['-v', '--verbose'],
    ['-V', '--version'],
    ['-ら', '--ライセンス'],
    ['-い', '--依存'],
    ['-☺', '--感謝'],
    // コマンドグループ
    ['-H', '--html'],
    ['-t', '--text'],
    ['-m', '--md-html'],
    ['-w', '--text-html'],
    ['-A', '--sample-text'],
    ['-B', '--sample-html'],
    ['-M', '--sample-md'],
    ['--readme-md'],
    ['--readme-html'],
    //
    ['-y', '--only-body'],
    ['-C', '--comment'],
    ['-K', '--katakana'],
    ['--switch'],
    ['--use-rp'],
  ],
  引数省略可: [
    ['-a', '--add-class'],
    ['-c', '--css'],
    ['--ruby-size'],
  ],
  排他的: [
    // コマンドグループ
    ['--html', '--text', '--add-class', '--md-html', '--text-html', '--sample-md', '--sample-text', '--sample-html'],
    // --htmlや--textを省略して自動判別にした場合、不要なオプションは無視
    ['--html', '--headline'],
    ['--html', '--brackets'],
    ['--html', '--switch'],
    //
    ['--text', '--selector'],
    ['--text', '--not-selector'],
    ['--text', '--ng-elements'],
    ['--text', '--css'],
    ['--text', '--title'],
    ['--text', '--use-rp'],
    ['--text', '--headline'],
    ['--text', '--only-body'],
    ['--text', '--ruby-size'],
    ['--text', '--switch'],
    //
    ['--add-class', '--brackets'],
    ['--add-class', '--grade'],
    ['--add-class', '--granularity'],
    ['--add-class', '--ng-elements'],
    ['--add-class', '--title'],
    ['--add-class', '--comment'],
    ['--add-class', '--katakana'],
    ['--add-class', '--use-rp'],
    ['--add-class', '--headline'],
    ['--add-class', '--ruby-size'],
    ['--add-class', '--ruby'],
    ['--add-class', '--ruby-comma'],
    ['--add-class', '--ruby-re'],
    //
    ['--md-html', '--brackets'],
    ['--md-html', '--grade'],
    ['--md-html', '--granularity'],
    ['--md-html', '--selector'],
    ['--md-html', '--not-selector'],
    ['--md-html', '--ng-elements'],
    ['--md-html', '--comment'],
    ['--md-html', '--katakana'],
    ['--md-html', '--use-rp'],
    ['--md-html', '--only-body'],
    ['--md-html', '--ruby-size'],
    ['--md-html', '--ruby'],
    ['--md-html', '--ruby-comma'],
    ['--md-html', '--ruby-re'],
    ['--md-html', '--switch'],
    //
    ['--text-html', '--brackets'],
    ['--text-html', '--grade'],
    ['--text-html', '--granularity'],
    ['--text-html', '--selector'],
    ['--text-html', '--not-selector'],
    ['--text-html', '--ng-elements'],
    ['--text-html', '--comment'],
    ['--text-html', '--katakana'],
    ['--text-html', '--use-rp'],
    ['--text-html', '--only-body'],
    ['--text-html', '--ruby-size'],
    ['--text-html', '--ruby'],
    ['--text-html', '--ruby-comma'],
    ['--text-html', '--ruby-re'],
    ['--text-html', '--switch'],
    // --only-body: --commentは出力ok
    ['--only-body', '--ruby-size'],
    ['--only-body', '--css'],
    ['--only-body', '--title'],
    // --sample-md, --sample-text, --sample-html, --readme-, --helpなどは、他のオプションをあっても無視
  ]
}
